/** Four prerecorded turns across two isolated live calls. No microphone/playback. */
import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
const [base,first,second,followup,out]=process.argv.slice(2);
const origin=new URL(base);if(!(origin.protocol==='http:'&&origin.hostname==='127.0.0.1')||origin.pathname!=='/'||origin.search||origin.username)throw Error('HTTPS origin required');
const paths=[first,second,followup], pcm=await Promise.all(paths.map(p=>fs.readFile(p)));
if(pcm.some(p=>p.length%2||p.length<6400||p.length>480000))throw Error('Raw PCM16 16kHz mono, 0.2–15 seconds required');
const report={application_revision:process.env.APPLICATION_REVISION||'unspecified',deployment_version:process.env.DEPLOYMENT_VERSION||'unspecified',started_at:new Date().toISOString(),scope:'Draft proposal in local Python Worker; four prerecorded turns; live providers; elapsed receipts; no deployed change, physical audio or performance acceptance',inputs:pcm.map(p=>({sha256:createHash('sha256').update(p).digest('hex'),seconds:p.length/32000})),passed:false,model_input_observation:'Restored persisted context and context-dependent answer; provider request arguments are verified by controlled tests, not captured by this live harness',calls:[],checks:[]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(f,label,ms=30000){const stop=Date.now()+ms;while(!f()){if(Date.now()>stop)throw Error('timeout_'+label);await sleep(20);}}
function send(c,v){if(c.ws.readyState===1)c.ws.send(JSON.stringify(v));}
async function connect(s){let c={s,events:[],receipts:0,scheduled:Date.now(),generation:-1,timers:new Set()};c.ws=new WebSocket(base.replace(/^http/,'ws')+'/api/session/'+s.id+'?token='+encodeURIComponent(s.token));c.ws.onmessage=e=>{let v=JSON.parse(e.data);if(v.type==='audio'){const b=Buffer.from(v.data,'base64');c.receipts++;c.scheduled=Math.max(c.scheduled,Date.now())+b.length/48;let t=setTimeout(()=>{c.timers.delete(t);send(c,{type:'played',generation:v.generation,chunk_id:v.chunk_id});c.receipts--;},Math.max(0,c.scheduled-Date.now()));c.timers.add(t);v={type:'audio',generation:v.generation,bytes:b.length,nonzero:b.some(x=>x!==0)};}if(v.type==='clear'){for(const t of c.timers)clearTimeout(t);c.timers.clear();c.receipts=0;c.scheduled=Date.now();}c.events.push(v);};try{await wait(()=>c.events.some(e=>e.type==='ready')||c.events.some(e=>e.type==='error'),'ready');if(c.events.some(e=>e.type==='error'))throw Error('startup_error');}catch(e){send(c,{type:'end'});await sleep(200);c.ws.close();throw e;}c.heartbeat=setInterval(()=>send(c,{type:'ping'}),10000);return c;}
async function create(){return(await fetch(base+'/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transport:'websocket'}),signal:AbortSignal.timeout(15000)})).json();}
async function turn(c,p){const start=c.events.length;let stopping=false;const feed=(async()=>{for(let i=0;i<p.length&&!stopping;i+=640){send(c,{type:'audio',data:p.subarray(i,i+640).toString('base64'),sample_rate:16000});await sleep(20);}for(let i=0;i<1500&&!stopping;i++){send(c,{type:'audio',data:Buffer.alloc(640).toString('base64'),sample_rate:16000});await sleep(20);}})();try{await wait(()=>{const e=c.events.slice(start);return e.some(v=>v.type==='error')||e.some(v=>v.type==='status'&&v.state==='listening')&&c.receipts===0;},'response',40000);const events=c.events.slice(start);if(events.some(v=>v.type==='error'))throw Error('turn_error');const users=events.filter(v=>v.type==='transcript'&&v.role==='user'&&v.final);if(users.length!==1)throw Error('wrong_turn_count');const answer=events.filter(v=>v.type==='transcript'&&v.role==='assistant').map(v=>v.text).join(' ');if(!answer||!events.some(v=>v.type==='audio'&&v.nonzero))throw Error('missing_answer_audio');return{user:users[0].text,answer,audio_bytes:events.filter(v=>v.type==='audio').reduce((s,v)=>s+v.bytes,0)};}finally{stopping=true;await feed;}}
async function disconnect(c){clearInterval(c.heartbeat);for(const t of c.timers)clearTimeout(t);c.ws.close(1000,'Context test reconnect');await wait(()=>c.ws.readyState===3,'disconnect',5000);}
const calls=[],sessions=[];try{for(let i=0;i<2;i++){const s=await create();sessions.push(s);const c=await connect(s);calls.push(c);const result=await turn(c,pcm[i]);report.calls.push({initial:result});if(!result.answer.toLowerCase().includes(i?'berlin':'paris'))throw Error('initial_answer');}
for(let i=0;i<2;i++){report.calls[i].connections=[calls[i].events];await disconnect(calls[i]);await sleep(300);calls[i]=await connect(sessions[i]);const history=calls[i].events.find(v=>v.type==='reset').history;report.calls[i].restored_history=history;const own=report.calls[i].initial.answer,other=report.calls[1-i].initial.answer;if(!history.some(m=>m.role==='assistant'&&m.content.trim()===own.trim()))throw Error('missing_committed_answer');if(history.some(m=>m.role==='assistant'&&m.content===other))throw Error('cross_call_context');const result=await turn(calls[i],pcm[2]);report.calls[i].followup=result;if(!result.answer.toLowerCase().includes(i?'germany':'france'))throw Error('context_followup_answer');}
report.checks.push('Each call restored its exact prior assistant answer after disconnect','No other call assistant answer appeared in restored context','Context-dependent follow-up correctly identified France and Germany','Each spoken turn produced exactly one final user transcript and nonzero response PCM');report.passed=true;
}catch(e){report.failure=String(e.message).replace(/https?:\S+/g,'[URL]');}finally{for(let i=0;i<calls.length;i++){const c=calls[i];clearInterval(c.heartbeat);for(const t of c.timers)clearTimeout(t);send(c,{type:'end'});try{await wait(()=>c.ws.readyState===3,'end',12000);const d=await(await fetch(base+'/api/session/'+sessions[i].id+'/diagnostics?token='+encodeURIComponent(sessions[i].token),{signal:AbortSignal.timeout(10000)})).json();report.calls[i]??={};report.calls[i].connections??=[];report.calls[i].connections.push(c.events);report.calls[i].turn_metrics=(d.metrics||[]).filter(m=>['user_end','turn_discarded','turn_pause','smart_turn','provider_error','response_error','generation_started'].includes(m.event));report.calls[i].cleanup=Object.fromEntries(['closed','pipecat_tasks','provider_tasks','provider_sockets','provider_readers','pending_provider_requests','pending_turn_requests','queued_output_bytes','unacked_audio_bytes','pending_playback_chunks','persistence_pending_writes'].filter(k=>Object.hasOwn(d,k)).map(k=>[k,d[k]]));if(Object.entries(report.calls[i].cleanup).some(([k,v])=>k==='closed'?!v:v!==0))report.passed=false;}catch{report.passed=false;report.cleanup_failure=true;}}report.finished_at=new Date().toISOString();await fs.writeFile(out,JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
